[package]
name = "lowpass-lr4-faust-nih-plug"
version = "0.1.0"
edition = "2021"
authors = ["obsoleszenz <obsoleszenz@riseup.net>"]
license = "GPL-3.0-or-later"
homepage = "codeberg.org/obsoleszenz"
description = "A short description of your plugin"

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Remove the `assert_process_allocs` feature to allow allocations on the audio
# thread in debug builds.
nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", features = ["assert_process_allocs"] }
# Uncomment the below line to disable the on-by-default VST3 feature to remove
# the GPL compatibility requirement
# nih_plug = { git = "https://github.com/robbert-vdh/nih-plug.git", default_features = false, features = ["assert_process_allocs"] }
faust-types = { git = "https://github.com/Frando/rust-faust" }

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"

[build-dependencies]
faust-build = { git = "https://github.com/Frando/rust-faust" }
faust-types = { git = "https://github.com/Frando/rust-faust" }
